---
# Source: guestbook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  namespace: guestbook-helm-rendered-dev
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: guestbook
  ports:
  - name: http
    port: 80
    targetPort: http
---
# Source: guestbook/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: guestbook-helm-rendered-dev
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: "ghcr.io/akuity/guestbook:v0.0.2"
        ports:
        - name: http
          containerPort: 3000
