apiVersion: ee.kargo.akuity.io/v1alpha1
kind: CustomPromotionStep
metadata:
  name: hello-world
spec:
  command:
    - sh
    - -c
    - |
      echo "This is a hello world custom promotion step with outputs"
      MSG="${{ config.message }}"

      echo "message: $MSG"
      printf 'message=%s' "$MSG" > $KARGO_OUTPUT
      
      # echo '{"message":"${{config.message}}"}' > /tmp/output.json
  image: busybox:1.37.0
  # output:
  #   source:
  #     path: /tmp/output.json
  #     type: File
