apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: hello
  annotations:
    # Sync before the other Kargo resources so the project namespace exists first.
    argocd.argoproj.io/sync-wave: "-1"
